#!/bin/bash

# Locate GPS device
sudo ./GPS_locator

#Locate DIGIRIG device
sudo ./Digirig_locator

# Install NTP and GPSd
sudo ./GPSD_install

# Build/install hamlib

sudo apt-get install autoconf automake libtool -y

cd $HOME/Programs
git clone https://github.com/Hamlib/Hamlib.git
cd Hamlib
./bootstrap
./configure
make
sudo make install


# Build/install direwolf

cd $HOME/Programs
sudo apt-get install git build-essential libasound2-dev libudev-dev alsa-utils rsyslog logrotate libgps-dev cmake libavahi-common-dev libavahi-client-dev -y

git clone http://github.com/wb2osz/direwolf
cd direwolf
mkdir build && cd build
cmake ..
make -j4
sudo make install

# install sound card
sudo ./soundcard_install

echo "############"
echo "REBOOT NOW"
